// Centralized brands constants for use in route.ts
export const OFFICE_SUPLY_BRANDS = [
  "The UPS Store",
  "FedEx",
  "OfficeDepot",
  "OfficeMax",
  "Staples",
];

export const PHARMACY_BRANDS = [
  "CVS",
  "Walgreens",
  "Rite Aid",
  "Duane Reade",
  "Walmart Pharmacy",
  "Target Pharmacy",
  "Kroger Pharmacy",
  "Publix Pharmacy",
  "Safeway Pharmacy",
  "Albertsons Pharmacy",
  "Costco Pharmacy",
  "Sam's Club Pharmacy",
  "Wegmans Pharmacy",
  "Meijer Pharmacy",
  "H-E-B Pharmacy",
  "Giant Pharmacy",
  "Hy-Vee Pharmacy",
  "Fred Meyer Pharmacy",
  "Longs Drugs",
  "Shoppers Drug Mart",
  "London Drugs",
  "Pharmacy",
  "Drugstore",
];

export const GAS_BRANDS = [
  "Shell",
  "Exxon",
  "Mobil",
  "Chevron",
  "BP",
  "Sunoco",
  "Marathon",
  "Phillips 66",
  "Valero",
  "Circle K",
  "Costco Gas",
  "Sam's Club Gas",
  "Speedway",
  "QuikTrip",
  "Wawa",
  "RaceTrac",
  "Love's",
  "Pilot",
  "Flying J",
  "Gulf",
  "Arco",
  "76",
  "Conoco",
  "Sinclair",
  "Hess",
  "Irving",
  "Casey's",
  "Holiday",
  "Sheetz",
  "GetGo",
  "Kwik Trip",
  "Kwik Fill",
  "Maverik",
  "Gas Station",
  "EV Charging Station",
  "Tesla Supercharger",
  "ChargePoint",
  "Electrify America",
  "EVgo",
  "Blink Charging",
  "Volta Charging",
  "Greenlots",
  "SemaConnect",
  "EV Connect",
  "EVBox",
  "EV Charging",
];

export const BANK_BRANDS = [
  "Chase",
  "Bank of America",
  "Wells Fargo",
  "Citibank",
  "US Bank",
  "PNC",
  "Capital One",
  "TD Bank",
  "BB&T",
  "SunTrust",
  "Regions",
  "Fifth Third",
  "KeyBank",
  "Huntington",
  "Santander",
  "M&T Bank",
  "BMO Harris",
  "Ally Bank",
  "Charles Schwab",
  "HSBC",
  "Citizens Bank",
  "First Republic",
  "Bank",
  "ATM",
];
