// Centralized deny regexps for filtering unwanted results in places API

export const NON_ASCII = /[^\x00-\x7F]/;

export const CONVENIENCE_WORDS = new RegExp(
  [
    "7\\s?-?\\s?eleven",
    "mini\\s?mart",
    "mart\\b",
    "liquor",
    "pharmacy",
    "drugstore",
    "deli",
    "bodega",
    "tobacco",
    "smoke",
    "vape",
    "grill",
    "kitchen",
    "cafe",
    "coffee",
    "restaurant",
    "pizza",
    "gas",
    "fuel",
    "quick\\s?shop",
    "quick\\s?stop",
  ].join("|"),
  "i"
);

export const SPECIALTY_CUES = new RegExp(
  [
    "international",
    "world",
    "african",
    "asian",
    "indian",
    "middle\\s*eastern",
    "halal",
    "kosher",
    "latin",
    "balkan",
    "bosn",
    "himalay",
    "european",
    "caribbean",
    "polish",
    "russian",
    "ukrain",
    "mexican",
    "italian",
    "spanish",
    "turkish",
    "greek",
    "japanese",
    "korean",
    "thai",
    "vietnam",
    "filipino",
    "persian",
    "arab",
    "ethiop",
    "somali",
    "jamaic",
    "trinidad",
    "pakist",
    "bangla",
    "nepal",
    "sri\\s*lanka",
    "brazil",
    "argentin",
    "peru",
    "colomb",
    "cuban",
    "puerto\\s*ric",
    // Added cues for cheese, pasta, fish, meat, bakery, deli, etc.
    "cheese",
    "pasta",
    "fish",
    "meat",
    "butcher",
    "seafood",
    "bakery",
    "deli",
    "gourmet",
    "artisan",
    "organic",
    "natural",
    "farmers",
    "produce",
    "olive oil",
    "spice",
    "tea",
    "wine",
    "liquor",
    "beer",
    "sausage",
    "smokehouse",
    "charcuterie",
    "salumeria",
    "fromager",
    "pescader",
    "carnicer",
    "panader",
    "pasteler",
    "formagger",
    "caseific",
    "boucher",
    "poissonner",
    "alimentari",
    "mercado",
    "mercato",
    "delicatessen",
    "provision",
    "fine food",
    "specialty food",
    "speciality food",
    "specialty market",
    "speciality market",
  ].join("|"),
  "i"
);

export const CHAIN_DENY = new RegExp(
  [
    "market\\s*basket",
    "walgreens",
    "\\bcvs\\b",
    "rite\\s*aid",
    "dunkin",
    "starbucks",
    "family\\s*dollar",
    "dollar\\s*general",
    "dollar\\s*tree",
    "walmart",
    "target",
    "costco",
    "bj'?s",
    "sam\\s*’s|sam\\s*\\bclub\\b|sam\\s*club",
  ].join("|"),
  "i"
);

export const PHARMACY_DENY = new RegExp(
  [
    "restaurant",
    "deli",
    "pizza",
    "grill",
    "kitchen",
    "cafe",
    "coffee",
    "liquor",
    "beer",
    "wine",
    "market basket",
    "walmart(?! pharmacy)",
    "target(?! pharmacy)",
    "costco(?! pharmacy)",
    "bj",
    "sam",
    "grocery",
    "supermarket",
    "bank",
    "atm",
    "auto",
    "repair",
    "dealer",
    "parts",
    "oil",
    "change",
    "station",
    "pet",
    "sport",
    "electronics",
    "office",
    "best buy",
    "staples",
    "dollar",
    "family dollar",
    "dollar general",
    "dollar tree",
    "7\\s?-?\\s?eleven",
    "convenience",
  ].join("|"),
  "i"
);

export const GAS_DENY = new RegExp(
  [
    "restaurant",
    "deli",
    "pizza",
    "grill",
    "kitchen",
    "cafe",
    "coffee",
    "liquor",
    "beer",
    "wine",
    "market basket",
    "bank",
    "atm",
    "auto repair",
    "dealer",
    "parts",
    "oil change",
    "stationery",
    "pet",
    "sport",
    "electronics",
    "office",
    "best buy",
    "staples",
    "dollar",
    "family dollar",
    "dollar general",
    "dollar tree",
    "pharmacy",
    "drugstore",
    "grocery",
    "supermarket",
  ].join("|"),
  "i"
);

export const BANK_DENY = new RegExp(
  [
    "restaurant",
    "deli",
    "pizza",
    "grill",
    "kitchen",
    "cafe",
    "coffee",
    "liquor",
    "beer",
    "wine",
    "market basket",
    "grocery",
    "supermarket",
    "pharmacy",
    "drugstore",
    "convenience",
    "auto",
    "repair",
    "dealer",
    "parts",
    "oil",
    "change",
    "stationery",
    "pet",
    "sport",
    "electronics",
    "office",
    "best buy",
    "staples",
    "dollar",
    "family dollar",
    "dollar general",
    "dollar tree",
    "gas",
    "ev charging",
    "shell",
    "exxon",
    "chevron",
    "bp",
    "sunoco",
    "marathon",
    "phillips 66",
    "valero",
    "circle k",
    "costco",
    "sam",
    "speedway",
    "quiktrip",
    "wawa",
    "racetrac",
    "loves",
    "pilot",
    "flying j",
    "gulf",
    "arco",
    "76",
    "conoco",
    "sinclair",
    "hess",
    "irving",
    "casey",
    "holiday",
    "sheetz",
    "getgo",
    "kwik trip",
    "kwik fill",
    "maverik",
    "tesla",
    "chargepoint",
    "electrify america",
    "evgo",
    "blink",
    "volta",
    "greenlots",
    "semaconnect",
    "ev connect",
    "evbox",
  ].join("|"),
  "i"
);

export const CLOTHING_CHAIN_DENY = new RegExp(
  [
    "walgreens",
    "cvs",
    "rite\\s*aid",
    "dollar\\s*tree",
    "dollar\\s*general",
    "family\\s*dollar",
    "walmart",
    "target",
    "costco",
    "bj'?s",
    "sam\\s*’s|sam\\s*\\bclub\\b|sam\\s*club",
    "pharmacy",
    "drugstore",
    "auto",
    "parts",
    "oil",
    "change",
    "repair",
    "dealer",
    "staples",
    "office",
    "electronics",
    "best\\s*buy",
    "pet",
    "sport",
    "grocery",
    "market",
    "supermarket",
    "liquor",
    "beer",
    "wine",
    "gas",
    "station",
    "convenience",
    "7\\s?-?\\s?eleven",
  ].join("|"),
  "i"
);

export const JEWELRY_CHAIN_DENY = new RegExp(
  [
    "pawn",
    "department",
    "pharmacy",
    "drugstore",
    "dollar",
    "walmart",
    "target",
    "costco",
    "bj",
    "sam",
    "auto",
    "parts",
    "oil",
    "change",
    "repair",
    "dealer",
    "staples",
    "office",
    "electronics",
    "pet",
    "sport",
    "grocery",
    "market",
    "supermarket",
    "liquor",
    "beer",
    "wine",
    "gas",
    "station",
    "convenience",
    "7\\s?-?\\s?eleven",
    "works",
    "technology",
  ].join("|"),
  "i"
);

export const PRINT_SHIP_DENY = new RegExp(
  [
    "access\\s*point",
    "drop\\s*box",
    "locker",
    "amazon\\s*hub",
  ].join("|"),
  "i"
);

export const BAR_VENUE_DENY = new RegExp(
  [
    "stadium",
    "arena",
    "center",
    "centre",
    "venue",
  ].join("|"),
  "i"
);

export const SPECIALTY_MARKETS_DENY = new RegExp(
  [
    "market\\s*basket",
    "whole\\s*foods",
    "trader\\s*joe'?s",
    "walmart",
    "target",
    "7\\s*-?\\s*eleven",
    "dunkin'?",
    "starbucks",
    "cvs",
    "walgreens",
    "stop\\s*&?\\s*shop",
    "shaw'?s",
    "ben\\s*&?\\s*jerry'?s",
  ].join("|"),
  "i"
);
